---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
  namespace: testname #jenkins
#namePrefix: jenkins-custom-
bases:
  - ../../base
patchesStrategicMerge:
  - patch.yaml
