---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
  labels:
    app: system
resources:
  - ../../apps/jenkins/overlays/dev
  - ../../apps/keycloak/overlays/dev
  - ../../apps/prometheus-stack/overlays/dev
