---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  ## Base bundle
  - flux-system
  - ../../apps/bundles/docker-range
  - 00-crds.yaml
  - 01-infra.yaml
  - 02-istio-rate-limits.yaml
  ## Customs
  # - flux-promotion
  - istio
  # - pg-airflow
  # - minio-loki
  # - redis
  # - clickhouse
patches:
  - path: victoria-metrics-k8s-stack/helm-release.yaml
