---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      version: "5.8.16"
      sourceRef:
        kind: HelmRepository
        name: jenkins
  interval: 30m
  test:
    enable: false
