---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      version: ">=1.14.0 <2.0.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress-private
  namespace: istio-ingress
spec:
  chart:
    spec:
      version: ">=1.14.0 <2.0.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: ">=0.18.0 <1.0.0"
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: external-secrets
#   namespace: external-secrets
# spec:
#   chart:
#     spec:
#       version: ">=0.0.1 <1.0.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      version: ">=5.0.0 <6.0.0"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: kubelinks
#   namespace: kubelinks
# spec:
#   chart:
#     spec:
#       version: ">=0.0.1 <1.0.0"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: blackbox-exporter
#   namespace: blackbox-exporter
# spec:
#   chart:
#     spec:
#       version: ">=9.0.0 <10.0.0"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: ">=v1.0.0 <v2.0.0"