---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/istio
  - ../../external-dns
  - ../../base/httpbin
  - ../../base/jenkins
  - ../../base/victoria-metrics-k8s-stack
  - ../../base/cert-manager
patches:
  - path: stable.yaml