---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      version: "1.24.3"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress-private
  namespace: istio-ingress
spec:
  chart:
    spec:
      version: "1.24.3"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: "0.36.2"
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: external-secrets
#   namespace: external-secrets
# spec:
#   chart:
#     spec:
#       version: "0.14.2"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      version: "5.8.16"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: kubelinks
#   namespace: kubelinks
# spec:
#   chart:
#     spec:
#       version: "0.4.10"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: blackbox-exporter
#   namespace: blackbox-exporter
# spec:
#   chart:
#     spec:
#       version: "9.2.0"

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: cert-manager
#   namespace: cert-manager
# spec:
#   chart:
#     spec:
#       version: "v1.17.1"