---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
  # - virtual-service.yaml
  # - gateway.yaml
