---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextjs-demo
  namespace: nextjs
spec:
  releaseName: nextjs-demo
  chart:
    spec:
      chart: nextjs-demo
      version: ">=1.0.0-alpha"
      sourceRef:
        kind: HelmRepository
        name: nextjs-demo
  interval: 30m
  test:
    enable: false
