apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system

  # install:
  #   crds: Skip
  #   remediation:
  #     retries: 3
  # upgrade:
  #   crds: Skip

  # Default values
  values:
    pilot:
      autoscaleMin: 1
    meshConfig:
      ingressClass: istio
      ingressService: istio-ingress-public
      ingressSelector: ingress-public
