---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: prometheus-stack
spec:
  interval: 5m
  url: https://drpalmeritta.github.io/palmeritta-helm-repo
