# ISTIO BASE/ISTIOD REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
spec:
  interval: 1m
  url: https://istio-release.storage.googleapis.com/charts

# ISTIO INGRESS REPOSITORY
# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: istio
# spec:
#   interval: 1m
#   url: https://istio-release.storage.googleapis.com/charts

# JENKINS REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
spec:
  interval: 1m
  url: https://drpalmeritta.github.io/palmeritta-helm-repo

# KEYCLOAK REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak
spec:
  interval: 5m
  url: https://drpalmeritta.github.io/palmeritta-helm-repo

# NEXTJS DEMO REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextjs-demo
spec:
  interval: 5m
  url: https://drpalmeritta.github.io/palmeritta-helm-repo

# PROMETHEUS STACK REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  url: https://drpalmeritta.github.io/palmeritta-helm-repo

# VICTORIA METRICS REPOSITORY
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm
spec:
  interval: 5m
  url: https://victoriametrics.github.io/helm-charts/
